name: Run All Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  compile_job:
    name: test_all
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lasp/adamant:latest
    steps:
      - run: echo "Starting job triggered by a ${{ github.event_name }} event on a ${{ runner.os }} server hosted by GitHub."
      - run: echo "Checking out ${{ github.repository }} on branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run all unit tests
        run: bash env/github_run.sh "redo test_all"
      - name: Archive logs for failed unit tests
        if: always() # Make sure this runs even if `redo test_all` fails
        uses: actions/upload-artifact@v3
        with:
          name: failed_test_logs
          path: ${{ github.workspace }}/build/failed_test_logs
          if-no-files-found: ignore
      - run: echo "Finished with status - ${{ job.status }}."
        if: always()
